
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Hiansdt", email = "vinijao123690@gmail.com"},
]
dependencies = [
    "django>=4.2.2",
    "celery>=5.3.1",
    "pika>=1.3.2",
]
requires-python = ">=3.10"
license = {text = "MIT"}
